# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#  name = "Demo"
#  url = "#hero"
#  weight = 10

[[main]]
  name = "About"
  url = "#about"
  weight = 10

[[main]]
  name = "Speakers"
  url = "#speakers"
  weight = 20

[[main]]
  name = "Program"
  url = "#program_R"
  weight = 30

[[main]]
  name = "Social events"
  url = "#submission"
  weight = 40
  
[[main]]
  name = "Poster session"
  url = "#important_dates"
  weight = 50

[[main]]
  name = "Committees"
  url = "#committees"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70


